### ISSUE TITLE
General todo / clean-up

### ISSUE THREAD

**Issue by sgtlambda** [kyranb/SoundCloud-Feed-Cleaner#7]
Since I'm interested in this project and I'd like to collaborate to its development, I've made a general to-do list which will give the project a head-start to become a more maintainable plugin for multiple collaborators.
- [ ] Re-format / re-indent code (`src/inject/sc-feed-cleaner.js` is messy right now and code style consistency will make it easier for multiple maintainers to work on this project at once)
- [ ] Remove external libraries from version tracking (there is a `js/jquery` folder right now, this might as well be an npm dependency)
- [ ] Remove the `.crx` file from the repository (this should be a "binary" attached to github releases)

Some lower priority things to consider as well:
- [ ] Seperate the .js source into multiple files and use `browserify` to bundle them up into a single `inject.js` (this would work nicely with the idea of installing `jquery` as an npm module as it would simply allow for `var $ = require('jquery');`)

**Comment by sgtlambda** [comment]
I myself don't have a lot of free time right now but once I do I would be willing to fix the issues in the above list.

**Comment by kyranb** [comment]
Thanks, I put this together pretty quickly for my own use. All of your proposals to tidy things up sound good. I've got a bit on myself right now, but would be happy to to help implement those suggestions in a few weeks time.
